---
#### Preamble ####
title: "Disparities in Climate-Induced Health Outcomes in the Greater Toronto Area."
author: "Sarah Mansoor"
email: "sarah.mansoor@mail.utoronto.ca"
thanks: "Code and data are available at: https://github.com/sarahmansoorr/SUDS2022"
date: "`r format(Sys.time(), '%d %B %Y')`"
format: pdf
editor: visual
abstract: "The growing impact of climate change in Canada demonstrates a clear and current threat to human health. These threats are becoming revealed in Canada as the country continues to face the consequences of warming almost at twice the global rate. The focus for this paper is on tempreture increases, lower air quality and more pollution and a decline in health for Toronto. Once the data for this research was collected, the data cleaning process begun which entailed of using packages in R like tidyverse, janitor, dplyr, …. Duplicate and irrelevant observations were removed, as well as unwanted outliers. The process was complete once the data was correct, consistent and usable. "
toc: true
bibliography: references.bib
---

## Introduction

As climate change worsens, the danger it presents to human health worsens as well. The health impacts from climate change are already being demonstrated in parts of Canada. Canada is warming at almost twice the global rate and if this continues, emissions will exceed 2 degrees celcius worldwide.

## Data

#### Data Collection

Temperature data was collected from ...

Pollution data was collected from ...

#### Variables of Interest

Tempreature variables of interest: Station Name, Date, Maximum temperature, Minimum temperature, Mean temperature.

Pollution varibales of interest: Pollutant, Month, Year, Average, StdDeviation

#### Data Processing

#### Population, Frame or Sample

## Visualizing the Data and the Implications

#### Visual 1

#### Implications 1

#### Visual 2

#### Implications 2

#### Visuals 3

#### Implications 3

## Limitations

## Results

## Next Steps

## Conclusion
